export const ActionTypes = {
  CHANGE_CURRENT_SOUND_SOURCE: 'CHANGE_CURRENT_SOUND_SOURCE',
  CHANGE_ANALYSER_STATE      : 'CHANGE_ANALYSER_STATE',
  CHANGE_MML_STATE           : 'CHANGE_MML_STATE'
};
