export const ActionTypes = {
  CHANGE_CURRENT_SOUND_SOURCE: 'CHANGE_CURRENT_SOUND_SOURCE',
  CHANGE_ANALYSER_STATE      : 'CHANGE_ANALYSER_STATE',
  CHANGE_MML_STATE           : 'CHANGE_MML_STATE',
  DOWN_KEYBOARDS             : 'DOWN_KEYBOARDS',
  UP_KEYBOARDS               : 'UP_KEYBOARDS'
};
