export const ActionTypes = {
  CHANGE_CURRENT_SOUND_SOURCE: 'CHANGE_CURRENT_SOUND_SOURCE',
  CHANGE_ANALYSER_STATE      : 'CHANGE_ANALYSER_STATE',
  CHANGE_MML_STATE           : 'CHANGE_MML_STATE',
  DOWN_MELODY_KEYBOARDS      : 'DOWN_MELODY_KEYBOARDS',
  DOWN_BASS_KEYBOARDS        : 'DOWN_BASS_KEYBOARDS',
  UP_MELODY_KEYBOARDS        : 'UP_MELODY_KEYBOARDS',
  UP_BASS_KEYBOARDS          : 'UP_BASS_KEYBOARDS',
  ACTIVATE_MIDI_KEYBOARDS    : 'ACTIVATE_MIDI_KEYBOARDS'
} as const;
